#!/bin/bash

docker build \
    --build-arg VCS_REF=$SOURCE_COMMIT \
    --build-arg BUILD_DATE=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) \
    --build-arg TTRSS_VERSION=$(git ls-remote https://git.tt-rss.org/fox/tt-rss master | head -1 | awk '{print $1}') \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .
