#!/bin/bash

docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_COMMIT
docker push $DOCKER_REPO:$SOURCE_COMMIT

TTRSS_VERSION=$(docker inspect --format '{{ index .Config.Labels "org.label-schema.version"}}' $IMAGE_NAME)
docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_COMMIT-$TTRSS_VERSION
docker push $DOCKER_REPO:$SOURCE_COMMIT-$TTRSS_VERSION
