name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Nightly to capture latest base image and ttrss version
  schedule:
    - cron:  '* 21 * * *'

  # Run tests for any PRs.
  pull_request:

jobs:
  dockerhub-registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: TTRSS version
        id: version
        run: |
          TTRSS_VERSION=$(git ls-remote https://git.tt-rss.org/fox/tt-rss master | head -1 | awk '{print $1}')

          echo "::set-output name=full::$TTRSS_VERSION"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            tingvarsson/ttrss
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=${{ steps.version.outputs.full }}
            type=raw,value=${{ github.sha }}-${{ steps.version.outputs.full }}
            type=sha,format=long,prefix=
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.full }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            TTRSS_VERSION=${{ steps.version.outputs.full }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
